import type { Bank } from '@/lib/types';

export interface CardTemplate {
  id: string;
  bank: Bank;
  cardName: string;
  fullName: string;
  network: 'visa' | 'mastercard' | 'rupay' | 'amex' | 'diners';
  gradient: string;
  textColor: string;
  accentColor: string;
  tier: 'entry' | 'mid' | 'premium' | 'super_premium';
}

export const CARD_TEMPLATES: CardTemplate[] = [
  // HDFC Bank (33 cards)
  {
    id: 'hdfc-regalia-gold',
    bank: 'hdfc',
    cardName: 'Regalia Gold',
    fullName: 'HDFC Bank Regalia Gold Credit Card',
    network: 'mastercard',
    gradient: 'linear-gradient(135deg, #0a2540 0%, #1a3a5c 50%, #0d3d5c 100%)',
    textColor: '#ffffff',
    accentColor: '#d4af37',
    tier: 'premium',
  },
  {
    id: 'hdfc-regalia',
    bank: 'hdfc',
    cardName: 'Regalia',
    fullName: 'HDFC Bank Regalia Credit Card',
    network: 'mastercard',
    gradient: 'linear-gradient(135deg, #004B87 0%, #0066a1 50%, #004B87 100%)',
    textColor: '#ffffff',
    accentColor: '#c9b896',
    tier: 'premium',
  },
  {
    id: 'hdfc-infinia',
    bank: 'hdfc',
    cardName: 'Infinia',
    fullName: 'HDFC Bank Infinia Credit Card',
    network: 'mastercard',
    gradient: 'linear-gradient(135deg, #0a0a0a 0%, #1a1a1a 30%, #2d2d2d 100%)',
    textColor: '#ffffff',
    accentColor: '#d4af37',
    tier: 'super_premium',
  },
  {
    id: 'hdfc-infinia-metal',
    bank: 'hdfc',
    cardName: 'Infinia Metal',
    fullName: 'HDFC Infinia Credit Card Metal Edition',
    network: 'mastercard',
    gradient: 'linear-gradient(135deg, #1a1a1a 0%, #2d2d2d 30%, #3d3d3d 70%, #1a1a1a 100%)',
    textColor: '#e0e0e0',
    accentColor: '#b0b0b0',
    tier: 'super_premium',
  },
  {
    id: 'hdfc-diners-black',
    bank: 'hdfc',
    cardName: 'Diners Club Black',
    fullName: 'HDFC Bank Diners Club Black Credit Card',
    network: 'diners',
    gradient: 'linear-gradient(135deg, #0d0d0d 0%, #1f1f1f 50%, #0a0a0a 100%)',
    textColor: '#ffffff',
    accentColor: '#d4af37',
    tier: 'super_premium',
  },
  {
    id: 'hdfc-diners-privilege',
    bank: 'hdfc',
    cardName: 'Diners Club Privilege',
    fullName: 'HDFC Bank Diners Club Privilege Credit Card',
    network: 'diners',
    gradient: 'linear-gradient(135deg, #0d2818 0%, #1a3d2e 50%, #0d2818 100%)',
    textColor: '#ffffff',
    accentColor: '#d4af37',
    tier: 'premium',
  },
  {
    id: 'hdfc-millennia',
    bank: 'hdfc',
    cardName: 'Millennia',
    fullName: 'HDFC Bank Millennia Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #4a148c 0%, #6a1b9a 50%, #7b1fa2 100%)',
    textColor: '#ffffff',
    accentColor: '#e1bee7',
    tier: 'mid',
  },
  {
    id: 'hdfc-moneyback-plus',
    bank: 'hdfc',
    cardName: 'MoneyBack+',
    fullName: 'HDFC Bank MoneyBack+ Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #1b5e20 0%, #2e7d32 50%, #388e3c 100%)',
    textColor: '#ffffff',
    accentColor: '#a5d6a7',
    tier: 'entry',
  },
  {
    id: 'hdfc-freedom',
    bank: 'hdfc',
    cardName: 'Freedom',
    fullName: 'HDFC Bank Freedom Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #e65100 0%, #ff6f00 50%, #ff8f00 100%)',
    textColor: '#ffffff',
    accentColor: '#ffe0b2',
    tier: 'entry',
  },
  {
    id: 'hdfc-swiggy',
    bank: 'hdfc',
    cardName: 'Swiggy',
    fullName: 'HDFC Bank Swiggy Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #fc8019 0%, #ff6b35 50%, #e85d04 100%)',
    textColor: '#ffffff',
    accentColor: '#ffffff',
    tier: 'entry',
  },
  {
    id: 'hdfc-tata-neu-plus',
    bank: 'hdfc',
    cardName: 'Tata Neu Plus',
    fullName: 'HDFC Bank Tata Neu Plus Credit Card',
    network: 'rupay',
    gradient: 'linear-gradient(135deg, #5e35b1 0%, #7e57c2 50%, #9575cd 100%)',
    textColor: '#ffffff',
    accentColor: '#d1c4e9',
    tier: 'mid',
  },
  {
    id: 'hdfc-tata-neu-infinity',
    bank: 'hdfc',
    cardName: 'Tata Neu Infinity',
    fullName: 'HDFC Bank Tata Neu Infinity Credit Card',
    network: 'rupay',
    gradient: 'linear-gradient(135deg, #4527a0 0%, #5e35b1 50%, #7e57c2 100%)',
    textColor: '#ffffff',
    accentColor: '#b39ddb',
    tier: 'premium',
  },
  {
    id: 'hdfc-indianoil',
    bank: 'hdfc',
    cardName: 'IndianOil',
    fullName: 'HDFC Bank IndianOil Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #01579b 0%, #0277bd 50%, #0288d1 100%)',
    textColor: '#ffffff',
    accentColor: '#ffeb3b',
    tier: 'mid',
  },
  {
    id: 'hdfc-upi-rupay',
    bank: 'hdfc',
    cardName: 'UPI RuPay',
    fullName: 'HDFC Bank UPI RuPay Credit Card',
    network: 'rupay',
    gradient: 'linear-gradient(135deg, #0d47a1 0%, #1565c0 50%, #1976d2 100%)',
    textColor: '#ffffff',
    accentColor: '#64b5f6',
    tier: 'entry',
  },
  {
    id: 'hdfc-shoppers-stop',
    bank: 'hdfc',
    cardName: 'Shoppers Stop',
    fullName: 'HDFC Bank Shoppers Stop Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #1a1a1a 0%, #2d2d2d 50%, #1a1a1a 100%)',
    textColor: '#ffffff',
    accentColor: '#d4af37',
    tier: 'mid',
  },
  {
    id: 'hdfc-marriott-bonvoy',
    bank: 'hdfc',
    cardName: 'Marriott Bonvoy',
    fullName: 'HDFC Bank Marriott Bonvoy Credit Card',
    network: 'mastercard',
    gradient: 'linear-gradient(135deg, #8b0000 0%, #a52a2a 50%, #b22222 100%)',
    textColor: '#ffffff',
    accentColor: '#d4af37',
    tier: 'premium',
  },
  {
    id: 'hdfc-bizpower',
    bank: 'hdfc',
    cardName: 'BizPower',
    fullName: 'HDFC Bank BizPower Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #004B87 0%, #0066a1 50%, #0077b6 100%)',
    textColor: '#ffffff',
    accentColor: '#90caf9',
    tier: 'mid',
  },
  {
    id: 'hdfc-pixel-play',
    bank: 'hdfc',
    cardName: 'Pixel Play',
    fullName: 'HDFC Bank Pixel Play Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #667eea 0%, #764ba2 50%, #f093fb 100%)',
    textColor: '#ffffff',
    accentColor: '#e1bee7',
    tier: 'entry',
  },
  {
    id: 'hdfc-6e-rewards',
    bank: 'hdfc',
    cardName: '6E Rewards',
    fullName: 'HDFC Bank 6E Rewards Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #0d47a1 0%, #1565c0 50%, #1e88e5 100%)',
    textColor: '#ffffff',
    accentColor: '#ffeb3b',
    tier: 'mid',
  },
  {
    id: 'hdfc-all-miles',
    bank: 'hdfc',
    cardName: 'All Miles',
    fullName: 'HDFC Bank All Miles Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #546e7a 0%, #78909c 50%, #90a4ae 100%)',
    textColor: '#ffffff',
    accentColor: '#cfd8dc',
    tier: 'mid',
  },
  {
    id: 'hdfc-platinum-edge',
    bank: 'hdfc',
    cardName: 'Platinum Edge',
    fullName: 'HDFC Bank Platinum Edge Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #455a64 0%, #607d8b 50%, #78909c 100%)',
    textColor: '#ffffff',
    accentColor: '#b0bec5',
    tier: 'entry',
  },
  {
    id: 'hdfc-smartbuy',
    bank: 'hdfc',
    cardName: 'SmartBuy',
    fullName: 'HDFC Bank SmartBuy Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #0d47a1 0%, #1976d2 50%, #42a5f5 100%)',
    textColor: '#ffffff',
    accentColor: '#90caf9',
    tier: 'mid',
  },
  {
    id: 'hdfc-jet-privilege',
    bank: 'hdfc',
    cardName: 'Jet Privilege',
    fullName: 'HDFC Bank Jet Privilege Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #1a237e 0%, #283593 50%, #3949ab 100%)',
    textColor: '#ffffff',
    accentColor: '#9fa8da',
    tier: 'premium',
  },
  {
    id: 'hdfc-times-points',
    bank: 'hdfc',
    cardName: 'Times Points',
    fullName: 'HDFC Bank Times Points Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #37474f 0%, #455a64 50%, #546e7a 100%)',
    textColor: '#ffffff',
    accentColor: '#b0bec5',
    tier: 'entry',
  },
  {
    id: 'hdfc-jet-sapphire',
    bank: 'hdfc',
    cardName: 'Jet Sapphire',
    fullName: 'HDFC Bank Jet Sapphire Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #0d47a1 0%, #1565c0 50%, #1976d2 100%)',
    textColor: '#ffffff',
    accentColor: '#64b5f6',
    tier: 'mid',
  },
  {
    id: 'hdfc-jet-platinum',
    bank: 'hdfc',
    cardName: 'Jet Platinum',
    fullName: 'HDFC Bank Jet Platinum Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #455a64 0%, #546e7a 50%, #607d8b 100%)',
    textColor: '#ffffff',
    accentColor: '#cfd8dc',
    tier: 'entry',
  },
  {
    id: 'hdfc-rupay-platinum',
    bank: 'hdfc',
    cardName: 'RuPay Platinum',
    fullName: 'HDFC Bank RuPay Platinum Credit Card',
    network: 'rupay',
    gradient: 'linear-gradient(135deg, #37474f 0%, #455a64 50%, #546e7a 100%)',
    textColor: '#ffffff',
    accentColor: '#b0bec5',
    tier: 'entry',
  },
  {
    id: 'hdfc-rupay-classic',
    bank: 'hdfc',
    cardName: 'RuPay Classic',
    fullName: 'HDFC Bank RuPay Classic Credit Card',
    network: 'rupay',
    gradient: 'linear-gradient(135deg, #004B87 0%, #0066a1 50%, #0077b6 100%)',
    textColor: '#ffffff',
    accentColor: '#90caf9',
    tier: 'entry',
  },
  {
    id: 'hdfc-business-regalia',
    bank: 'hdfc',
    cardName: 'Business Regalia',
    fullName: 'HDFC Bank Business Regalia Credit Card',
    network: 'mastercard',
    gradient: 'linear-gradient(135deg, #004B87 0%, #1a3a5c 50%, #004B87 100%)',
    textColor: '#ffffff',
    accentColor: '#c9b896',
    tier: 'premium',
  },
  {
    id: 'hdfc-business-moneyback',
    bank: 'hdfc',
    cardName: 'Business MoneyBack',
    fullName: 'HDFC Bank Business MoneyBack Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #1b5e20 0%, #2e7d32 50%, #388e3c 100%)',
    textColor: '#ffffff',
    accentColor: '#a5d6a7',
    tier: 'mid',
  },
  {
    id: 'hdfc-women-exclusive',
    bank: 'hdfc',
    cardName: 'Women Exclusive',
    fullName: 'HDFC Bank Women Exclusive Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #880e4f 0%, #ad1457 50%, #c2185b 100%)',
    textColor: '#ffffff',
    accentColor: '#f8bbd0',
    tier: 'mid',
  },
  {
    id: 'hdfc-student',
    bank: 'hdfc',
    cardName: 'Student',
    fullName: 'HDFC Bank Student Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #004B87 0%, #1565c0 50%, #42a5f5 100%)',
    textColor: '#ffffff',
    accentColor: '#90caf9',
    tier: 'entry',
  },
  {
    id: 'hdfc-superia',
    bank: 'hdfc',
    cardName: 'Superia',
    fullName: 'HDFC Bank Superia Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #1a237e 0%, #283593 50%, #3949ab 100%)',
    textColor: '#ffffff',
    accentColor: '#9fa8da',
    tier: 'premium',
  },
  {
    id: 'hdfc-rupay-millennia',
    bank: 'hdfc',
    cardName: 'RuPay Millennia',
    fullName: 'HDFC Bank RuPay Millennia Credit Card',
    network: 'rupay',
    gradient: 'linear-gradient(135deg, #4a148c 0%, #6a1b9a 50%, #7b1fa2 100%)',
    textColor: '#ffffff',
    accentColor: '#e1bee7',
    tier: 'mid',
  },
  {
    id: 'hdfc-digital',
    bank: 'hdfc',
    cardName: 'Digital',
    fullName: 'HDFC Bank Digital Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #0d47a1 0%, #1565c0 50%, #42a5f5 100%)',
    textColor: '#ffffff',
    accentColor: '#64b5f6',
    tier: 'entry',
  },

  // ICICI Bank (33 cards)
  {
    id: 'icici-amazon-pay',
    bank: 'icici',
    cardName: 'Amazon Pay',
    fullName: 'ICICI Bank Amazon Pay Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #232f3e 0%, #37475a 50%, #232f3e 100%)',
    textColor: '#ffffff',
    accentColor: '#ff9900',
    tier: 'mid',
  },
  {
    id: 'icici-coral',
    bank: 'icici',
    cardName: 'Coral',
    fullName: 'ICICI Bank Coral Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #ff7043 0%, #ff8a65 50%, #ffab91 100%)',
    textColor: '#ffffff',
    accentColor: '#ffe0b2',
    tier: 'entry',
  },
  {
    id: 'icici-rubyx',
    bank: 'icici',
    cardName: 'Rubyx',
    fullName: 'ICICI Bank Rubyx Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #880e4f 0%, #ad1457 50%, #c2185b 100%)',
    textColor: '#ffffff',
    accentColor: '#f8bbd0',
    tier: 'premium',
  },
  {
    id: 'icici-sapphiro',
    bank: 'icici',
    cardName: 'Sapphiro',
    fullName: 'ICICI Bank Sapphiro Credit Card',
    network: 'mastercard',
    gradient: 'linear-gradient(135deg, #0d47a1 0%, #1565c0 50%, #1976d2 100%)',
    textColor: '#ffffff',
    accentColor: '#64b5f6',
    tier: 'premium',
  },
  {
    id: 'icici-emeralde',
    bank: 'icici',
    cardName: 'Emeralde',
    fullName: 'ICICI Bank Emeralde Credit Card',
    network: 'mastercard',
    gradient: 'linear-gradient(135deg, #004d40 0%, #00695c 50%, #00796b 100%)',
    textColor: '#ffffff',
    accentColor: '#80cbc4',
    tier: 'super_premium',
  },
  {
    id: 'icici-makemytrip',
    bank: 'icici',
    cardName: 'MakeMyTrip',
    fullName: 'ICICI Bank MakeMyTrip Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #d32f2f 0%, #f44336 50%, #ff5722 100%)',
    textColor: '#ffffff',
    accentColor: '#ffccbc',
    tier: 'mid',
  },
  {
    id: 'icici-manchester-united',
    bank: 'icici',
    cardName: 'Manchester United Platinum',
    fullName: 'ICICI Bank Manchester United Platinum Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #1a1a1a 0%, #b71c1c 50%, #1a1a1a 100%)',
    textColor: '#ffffff',
    accentColor: '#ffeb3b',
    tier: 'mid',
  },
  {
    id: 'icici-platinum-chip',
    bank: 'icici',
    cardName: 'Platinum Chip',
    fullName: 'ICICI Bank Platinum Chip Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #455a64 0%, #546e7a 50%, #607d8b 100%)',
    textColor: '#ffffff',
    accentColor: '#cfd8dc',
    tier: 'entry',
  },
  {
    id: 'icici-hpcl-super-saver',
    bank: 'icici',
    cardName: 'HPCL Super Saver',
    fullName: 'ICICI Bank HPCL Super Saver Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #1b5e20 0%, #2e7d32 50%, #0d47a1 100%)',
    textColor: '#ffffff',
    accentColor: '#81c784',
    tier: 'mid',
  },
  {
    id: 'icici-expressions',
    bank: 'icici',
    cardName: 'Expressions',
    fullName: 'ICICI Bank Expressions Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #e91e63 0%, #9c27b0 50%, #673ab7 100%)',
    textColor: '#ffffff',
    accentColor: '#e1bee7',
    tier: 'entry',
  },
  {
    id: 'icici-ferrari-platinum',
    bank: 'icici',
    cardName: 'Ferrari Platinum',
    fullName: 'ICICI Bank Ferrari Platinum Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #b71c1c 0%, #d32f2f 50%, #f44336 100%)',
    textColor: '#ffffff',
    accentColor: '#ffcdd2',
    tier: 'premium',
  },
  {
    id: 'icici-gemstone',
    bank: 'icici',
    cardName: 'Gemstone',
    fullName: 'ICICI Bank Gemstone Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #4a148c 0%, #7b1fa2 50%, #ab47bc 100%)',
    textColor: '#ffffff',
    accentColor: '#e1bee7',
    tier: 'mid',
  },
  {
    id: 'icici-jet-airways',
    bank: 'icici',
    cardName: 'Jet Airways',
    fullName: 'ICICI Bank Jet Airways Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #1a237e 0%, #283593 50%, #3949ab 100%)',
    textColor: '#ffffff',
    accentColor: '#9fa8da',
    tier: 'premium',
  },
  {
    id: 'icici-hpcl-coral',
    bank: 'icici',
    cardName: 'HPCL Coral',
    fullName: 'ICICI Bank HPCL Coral Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #ff7043 0%, #1b5e20 50%, #1565c0 100%)',
    textColor: '#ffffff',
    accentColor: '#ffcc80',
    tier: 'mid',
  },
  {
    id: 'icici-bpcl',
    bank: 'icici',
    cardName: 'BPCL',
    fullName: 'ICICI Bank BPCL Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #1b5e20 0%, #2e7d32 50%, #ffeb3b 100%)',
    textColor: '#ffffff',
    accentColor: '#c8e6c9',
    tier: 'mid',
  },
  {
    id: 'icici-rupay-coral',
    bank: 'icici',
    cardName: 'RuPay Coral',
    fullName: 'ICICI Bank RuPay Coral Credit Card',
    network: 'rupay',
    gradient: 'linear-gradient(135deg, #ff7043 0%, #ff8a65 50%, #ffab91 100%)',
    textColor: '#ffffff',
    accentColor: '#ffe0b2',
    tier: 'entry',
  },
  {
    id: 'icici-instant',
    bank: 'icici',
    cardName: 'Instant',
    fullName: 'ICICI Bank Instant Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #f58220 0%, #ff9800 50%, #ffb74d 100%)',
    textColor: '#ffffff',
    accentColor: '#ffe0b2',
    tier: 'entry',
  },
  {
    id: 'icici-holiday',
    bank: 'icici',
    cardName: 'Holiday',
    fullName: 'ICICI Bank Holiday Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #00796b 0%, #00897b 50%, #26a69a 100%)',
    textColor: '#ffffff',
    accentColor: '#b2dfdb',
    tier: 'mid',
  },
  {
    id: 'icici-rupay-platinum',
    bank: 'icici',
    cardName: 'RuPay Platinum',
    fullName: 'ICICI Bank RuPay Platinum Credit Card',
    network: 'rupay',
    gradient: 'linear-gradient(135deg, #455a64 0%, #546e7a 50%, #607d8b 100%)',
    textColor: '#ffffff',
    accentColor: '#cfd8dc',
    tier: 'entry',
  },
  {
    id: 'icici-pockets',
    bank: 'icici',
    cardName: 'Pockets',
    fullName: 'ICICI Bank Pockets Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #e65100 0%, #ff6f00 50%, #ff9800 100%)',
    textColor: '#ffffff',
    accentColor: '#ffe0b2',
    tier: 'entry',
  },
  {
    id: 'icici-bank-itr',
    bank: 'icici',
    cardName: 'Bank ITR',
    fullName: 'ICICI Bank ITR Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #37474f 0%, #455a64 50%, #546e7a 100%)',
    textColor: '#ffffff',
    accentColor: '#b0bec5',
    tier: 'entry',
  },
  {
    id: 'icici-apex',
    bank: 'icici',
    cardName: 'Apex',
    fullName: 'ICICI Bank Apex Credit Card',
    network: 'mastercard',
    gradient: 'linear-gradient(135deg, #0a0a0a 0%, #1a1a1a 50%, #2d2d2d 100%)',
    textColor: '#ffffff',
    accentColor: '#d4af37',
    tier: 'super_premium',
  },
  {
    id: 'icici-signature',
    bank: 'icici',
    cardName: 'Signature',
    fullName: 'ICICI Bank Signature Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #004d40 0%, #00695c 50%, #00796b 100%)',
    textColor: '#ffffff',
    accentColor: '#80cbc4',
    tier: 'premium',
  },
  {
    id: 'icici-dual',
    bank: 'icici',
    cardName: 'Dual',
    fullName: 'ICICI Bank Dual Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #f58220 0%, #1565c0 50%, #f58220 100%)',
    textColor: '#ffffff',
    accentColor: '#ffcc80',
    tier: 'mid',
  },
  {
    id: 'icici-student',
    bank: 'icici',
    cardName: 'Student',
    fullName: 'ICICI Bank Student Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #f58220 0%, #ff9800 50%, #ffb74d 100%)',
    textColor: '#ffffff',
    accentColor: '#ffe0b2',
    tier: 'entry',
  },
  {
    id: 'icici-women-exclusive',
    bank: 'icici',
    cardName: 'Women Exclusive',
    fullName: 'ICICI Bank Women Exclusive Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #ad1457 0%, #c2185b 50%, #e91e63 100%)',
    textColor: '#ffffff',
    accentColor: '#f8bbd0',
    tier: 'mid',
  },
  {
    id: 'icici-business',
    bank: 'icici',
    cardName: 'Business',
    fullName: 'ICICI Bank Business Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #37474f 0%, #455a64 50%, #546e7a 100%)',
    textColor: '#ffffff',
    accentColor: '#b0bec5',
    tier: 'mid',
  },
  {
    id: 'icici-titanium',
    bank: 'icici',
    cardName: 'Titanium',
    fullName: 'ICICI Bank Titanium Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #455a64 0%, #546e7a 50%, #78909c 100%)',
    textColor: '#ffffff',
    accentColor: '#cfd8dc',
    tier: 'entry',
  },
  {
    id: 'icici-rupay-rubyx',
    bank: 'icici',
    cardName: 'RuPay Rubyx',
    fullName: 'ICICI Bank RuPay Rubyx Credit Card',
    network: 'rupay',
    gradient: 'linear-gradient(135deg, #880e4f 0%, #ad1457 50%, #c2185b 100%)',
    textColor: '#ffffff',
    accentColor: '#f8bbd0',
    tier: 'premium',
  },
  {
    id: 'icici-videocon',
    bank: 'icici',
    cardName: 'Videocon',
    fullName: 'ICICI Bank Videocon Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #d32f2f 0%, #f44336 50%, #e53935 100%)',
    textColor: '#ffffff',
    accentColor: '#ffcdd2',
    tier: 'entry',
  },
  {
    id: 'icici-jet-privilege',
    bank: 'icici',
    cardName: 'Jet Privilege',
    fullName: 'ICICI Bank Jet Privilege Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #1a237e 0%, #283593 50%, #3949ab 100%)',
    textColor: '#ffffff',
    accentColor: '#9fa8da',
    tier: 'premium',
  },
  {
    id: 'icici-amex-platinum',
    bank: 'icici',
    cardName: 'Amex Platinum',
    fullName: 'ICICI Bank Amex Platinum Credit Card',
    network: 'amex',
    gradient: 'linear-gradient(135deg, #0d47a1 0%, #1565c0 50%, #1976d2 100%)',
    textColor: '#ffffff',
    accentColor: '#64b5f6',
    tier: 'premium',
  },
  {
    id: 'icici-amex-gold',
    bank: 'icici',
    cardName: 'Amex Gold',
    fullName: 'ICICI Bank Amex Gold Credit Card',
    network: 'amex',
    gradient: 'linear-gradient(135deg, #f9a825 0%, #ffb300 50%, #ffc107 100%)',
    textColor: '#000000',
    accentColor: '#ffd54f',
    tier: 'mid',
  },
  {
    id: 'icici-amex-coral',
    bank: 'icici',
    cardName: 'Amex Coral',
    fullName: 'ICICI Bank Amex Coral Credit Card',
    network: 'amex',
    gradient: 'linear-gradient(135deg, #ff7043 0%, #ff8a65 50%, #ffab91 100%)',
    textColor: '#ffffff',
    accentColor: '#ffe0b2',
    tier: 'entry',
  },
  {
    id: 'icici-digital',
    bank: 'icici',
    cardName: 'Digital',
    fullName: 'ICICI Bank Digital Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #f58220 0%, #ff9800 50%, #42a5f5 100%)',
    textColor: '#ffffff',
    accentColor: '#90caf9',
    tier: 'entry',
  },

  // Axis Bank (34 cards)
  {
    id: 'axis-flipkart',
    bank: 'axis',
    cardName: 'Flipkart',
    fullName: 'Axis Bank Flipkart Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #2874f0 0%, #1a5fd4 50%, #ffeb3b 100%)',
    textColor: '#ffffff',
    accentColor: '#ffffff',
    tier: 'mid',
  },
  {
    id: 'axis-magnus',
    bank: 'axis',
    cardName: 'Magnus',
    fullName: 'Axis Bank Magnus Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #0a0a0a 0%, #1a1a1a 30%, #2d2d2d 100%)',
    textColor: '#ffffff',
    accentColor: '#d4af37',
    tier: 'super_premium',
  },
  {
    id: 'axis-reserve',
    bank: 'axis',
    cardName: 'Reserve',
    fullName: 'Axis Bank Reserve Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #0a1628 0%, #0d2137 50%, #132f4c 100%)',
    textColor: '#ffffff',
    accentColor: '#d4af37',
    tier: 'super_premium',
  },
  {
    id: 'axis-privilege',
    bank: 'axis',
    cardName: 'Privilege',
    fullName: 'Axis Bank Privilege Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #97144D 0%, #b71c6b 50%, #97144D 100%)',
    textColor: '#ffffff',
    accentColor: '#e1bee7',
    tier: 'premium',
  },
  {
    id: 'axis-my-zone',
    bank: 'axis',
    cardName: 'MY Zone',
    fullName: 'Axis Bank MY Zone Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #4a148c 0%, #6a1b9a 50%, #7b1fa2 100%)',
    textColor: '#ffffff',
    accentColor: '#e1bee7',
    tier: 'entry',
  },
  {
    id: 'axis-ace',
    bank: 'axis',
    cardName: 'Ace',
    fullName: 'Axis Bank Ace Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #b71c1c 0%, #1a1a1a 50%, #b71c1c 100%)',
    textColor: '#ffffff',
    accentColor: '#ffcdd2',
    tier: 'mid',
  },
  {
    id: 'axis-neo',
    bank: 'axis',
    cardName: 'Neo',
    fullName: 'Axis Bank Neo Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #00bcd4 0%, #26c6da 50%, #4dd0e1 100%)',
    textColor: '#ffffff',
    accentColor: '#b2ebf2',
    tier: 'entry',
  },
  {
    id: 'axis-select',
    bank: 'axis',
    cardName: 'Select',
    fullName: 'Axis Bank Select Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #b8860b 0%, #daa520 50%, #ffd700 100%)',
    textColor: '#000000',
    accentColor: '#ffeb3b',
    tier: 'premium',
  },
  {
    id: 'axis-vistara',
    bank: 'axis',
    cardName: 'Vistara',
    fullName: 'Axis Bank Vistara Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #0d47a1 0%, #1565c0 50%, #ffd700 100%)',
    textColor: '#ffffff',
    accentColor: '#ffeb3b',
    tier: 'mid',
  },
  {
    id: 'axis-vistara-signature',
    bank: 'axis',
    cardName: 'Vistara Signature',
    fullName: 'Axis Bank Vistara Signature Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #0a1628 0%, #0d47a1 50%, #ffd700 100%)',
    textColor: '#ffffff',
    accentColor: '#d4af37',
    tier: 'premium',
  },
  {
    id: 'axis-vistara-infinite',
    bank: 'axis',
    cardName: 'Vistara Infinite',
    fullName: 'Axis Bank Vistara Infinite Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #0a0a14 0%, #1a1a3e 50%, #d4af37 100%)',
    textColor: '#ffffff',
    accentColor: '#d4af37',
    tier: 'super_premium',
  },
  {
    id: 'axis-atlas',
    bank: 'axis',
    cardName: 'Atlas',
    fullName: 'Axis Bank Atlas Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #455a64 0%, #546e7a 50%, #1976d2 100%)',
    textColor: '#ffffff',
    accentColor: '#90caf9',
    tier: 'premium',
  },
  {
    id: 'axis-samsung-infinite',
    bank: 'axis',
    cardName: 'Samsung Infinite',
    fullName: 'Axis Bank Samsung Infinite Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #0a0a0a 0%, #1a1a1a 50%, #2d2d2d 100%)',
    textColor: '#ffffff',
    accentColor: '#64b5f6',
    tier: 'super_premium',
  },
  {
    id: 'axis-indian-oil',
    bank: 'axis',
    cardName: 'Indian Oil',
    fullName: 'Axis Bank Indian Oil Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #1b5e20 0%, #2e7d32 50%, #388e3c 100%)',
    textColor: '#ffffff',
    accentColor: '#81c784',
    tier: 'mid',
  },
  {
    id: 'axis-airtel',
    bank: 'axis',
    cardName: 'Airtel',
    fullName: 'Axis Bank Airtel Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #e4002b 0%, #ff1744 50%, #e4002b 100%)',
    textColor: '#ffffff',
    accentColor: '#ffcdd2',
    tier: 'entry',
  },
  {
    id: 'axis-lic',
    bank: 'axis',
    cardName: 'LIC',
    fullName: 'Axis Bank LIC Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #0d47a1 0%, #1565c0 50%, #1976d2 100%)',
    textColor: '#ffffff',
    accentColor: '#64b5f6',
    tier: 'mid',
  },
  {
    id: 'axis-freecharge-plus',
    bank: 'axis',
    cardName: 'Freecharge Plus',
    fullName: 'Axis Bank Freecharge Plus Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #1b5e20 0%, #2e7d32 50%, #43a047 100%)',
    textColor: '#ffffff',
    accentColor: '#a5d6a7',
    tier: 'entry',
  },
  {
    id: 'axis-burgundy-private',
    bank: 'axis',
    cardName: 'Burgundy Private',
    fullName: 'Axis Bank Burgundy Private Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #4a0e0e 0%, #6b1a1a 50%, #8b2222 100%)',
    textColor: '#ffffff',
    accentColor: '#d4af37',
    tier: 'super_premium',
  },
  {
    id: 'axis-burgundy',
    bank: 'axis',
    cardName: 'Burgundy',
    fullName: 'Axis Bank Burgundy Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #6b1a1a 0%, #8b2222 50%, #97144D 100%)',
    textColor: '#ffffff',
    accentColor: '#e1bee7',
    tier: 'premium',
  },
  {
    id: 'axis-escape',
    bank: 'axis',
    cardName: 'Escape',
    fullName: 'Axis Bank Escape Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #00796b 0%, #00897b 50%, #26a69a 100%)',
    textColor: '#ffffff',
    accentColor: '#b2dfdb',
    tier: 'mid',
  },
  {
    id: 'axis-instant',
    bank: 'axis',
    cardName: 'Instant',
    fullName: 'Axis Bank Instant Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #97144D 0%, #b71c6b 50%, #e91e63 100%)',
    textColor: '#ffffff',
    accentColor: '#f8bbd0',
    tier: 'entry',
  },
  {
    id: 'axis-platinum',
    bank: 'axis',
    cardName: 'Platinum',
    fullName: 'Axis Bank Platinum Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #455a64 0%, #546e7a 50%, #607d8b 100%)',
    textColor: '#ffffff',
    accentColor: '#cfd8dc',
    tier: 'entry',
  },
  {
    id: 'axis-signature',
    bank: 'axis',
    cardName: 'Signature',
    fullName: 'Axis Bank Signature Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #97144D 0%, #b71c6b 50%, #e91e63 100%)',
    textColor: '#ffffff',
    accentColor: '#f8bbd0',
    tier: 'premium',
  },
  {
    id: 'axis-rupay-platinum',
    bank: 'axis',
    cardName: 'RuPay Platinum',
    fullName: 'Axis Bank RuPay Platinum Credit Card',
    network: 'rupay',
    gradient: 'linear-gradient(135deg, #455a64 0%, #546e7a 50%, #607d8b 100%)',
    textColor: '#ffffff',
    accentColor: '#cfd8dc',
    tier: 'entry',
  },
  {
    id: 'axis-rupay-select',
    bank: 'axis',
    cardName: 'RuPay Select',
    fullName: 'Axis Bank RuPay Select Credit Card',
    network: 'rupay',
    gradient: 'linear-gradient(135deg, #b8860b 0%, #daa520 50%, #ffd700 100%)',
    textColor: '#000000',
    accentColor: '#ffeb3b',
    tier: 'premium',
  },
  {
    id: 'axis-mydesign',
    bank: 'axis',
    cardName: 'MyDesign',
    fullName: 'Axis Bank MyDesign Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #e91e63 0%, #9c27b0 50%, #673ab7 100%)',
    textColor: '#ffffff',
    accentColor: '#e1bee7',
    tier: 'entry',
  },
  {
    id: 'axis-iol-platinum',
    bank: 'axis',
    cardName: 'IOL Platinum',
    fullName: 'Axis Bank IOL Platinum Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #1b5e20 0%, #2e7d32 50%, #388e3c 100%)',
    textColor: '#ffffff',
    accentColor: '#81c784',
    tier: 'mid',
  },
  {
    id: 'axis-samsung-signature',
    bank: 'axis',
    cardName: 'Samsung Signature',
    fullName: 'Axis Bank Samsung Signature Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #37474f 0%, #455a64 50%, #546e7a 100%)',
    textColor: '#ffffff',
    accentColor: '#90caf9',
    tier: 'premium',
  },
  {
    id: 'axis-travel',
    bank: 'axis',
    cardName: 'Travel',
    fullName: 'Axis Bank Travel Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #0d47a1 0%, #1565c0 50%, #1976d2 100%)',
    textColor: '#ffffff',
    accentColor: '#64b5f6',
    tier: 'mid',
  },
  {
    id: 'axis-rewards',
    bank: 'axis',
    cardName: 'Rewards',
    fullName: 'Axis Bank Rewards Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #97144D 0%, #b71c6b 50%, #e91e63 100%)',
    textColor: '#ffffff',
    accentColor: '#f8bbd0',
    tier: 'entry',
  },
  {
    id: 'axis-student',
    bank: 'axis',
    cardName: 'Student',
    fullName: 'Axis Bank Student Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #97144D 0%, #b71c6b 50%, #e91e63 100%)',
    textColor: '#ffffff',
    accentColor: '#f8bbd0',
    tier: 'entry',
  },
  {
    id: 'axis-women-exclusive',
    bank: 'axis',
    cardName: 'Women Exclusive',
    fullName: 'Axis Bank Women Exclusive Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #ad1457 0%, #c2185b 50%, #e91e63 100%)',
    textColor: '#ffffff',
    accentColor: '#f8bbd0',
    tier: 'mid',
  },
  {
    id: 'axis-business',
    bank: 'axis',
    cardName: 'Business',
    fullName: 'Axis Bank Business Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #37474f 0%, #455a64 50%, #546e7a 100%)',
    textColor: '#ffffff',
    accentColor: '#b0bec5',
    tier: 'mid',
  },
  {
    id: 'axis-digital',
    bank: 'axis',
    cardName: 'Digital',
    fullName: 'Axis Bank Digital Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #97144D 0%, #1565c0 50%, #42a5f5 100%)',
    textColor: '#ffffff',
    accentColor: '#90caf9',
    tier: 'entry',
  },
  {
    id: 'axis-rupay-magnus',
    bank: 'axis',
    cardName: 'RuPay Magnus',
    fullName: 'Axis Bank RuPay Magnus Credit Card',
    network: 'rupay',
    gradient: 'linear-gradient(135deg, #0a0a0a 0%, #1a1a1a 30%, #2d2d2d 100%)',
    textColor: '#ffffff',
    accentColor: '#d4af37',
    tier: 'super_premium',
  },
  {
    id: 'axis-rupay-ace',
    bank: 'axis',
    cardName: 'RuPay Ace',
    fullName: 'Axis Bank RuPay Ace Credit Card',
    network: 'rupay',
    gradient: 'linear-gradient(135deg, #b71c1c 0%, #1a1a1a 50%, #b71c1c 100%)',
    textColor: '#ffffff',
    accentColor: '#ffcdd2',
    tier: 'mid',
  },
  {
    id: 'axis-rupay-flipkart',
    bank: 'axis',
    cardName: 'RuPay Flipkart',
    fullName: 'Axis Bank RuPay Flipkart Credit Card',
    network: 'rupay',
    gradient: 'linear-gradient(135deg, #2874f0 0%, #1a5fd4 50%, #ffeb3b 100%)',
    textColor: '#ffffff',
    accentColor: '#ffffff',
    tier: 'mid',
  },
  {
    id: 'axis-rupay-airtel',
    bank: 'axis',
    cardName: 'RuPay Airtel',
    fullName: 'Axis Bank RuPay Airtel Credit Card',
    network: 'rupay',
    gradient: 'linear-gradient(135deg, #e4002b 0%, #ff1744 50%, #e4002b 100%)',
    textColor: '#ffffff',
    accentColor: '#ffcdd2',
    tier: 'entry',
  },

  // SBI Card
  {
    id: 'sbi-cashback',
    bank: 'sbi',
    cardName: 'Cashback',
    fullName: 'Cashback SBI Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #1a5276 0%, #2980b9 50%, #3498db 100%)',
    textColor: '#ffffff',
    accentColor: '#85c1e9',
    tier: 'mid',
  },
  {
    id: 'sbi-simplyclick',
    bank: 'sbi',
    cardName: 'SimplyCLICK',
    fullName: 'SBI SimplyCLICK Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #1a237e 0%, #283593 50%, #3949ab 100%)',
    textColor: '#ffffff',
    accentColor: '#7986cb',
    tier: 'mid',
  },
  {
    id: 'sbi-simplysave',
    bank: 'sbi',
    cardName: 'SimplySAVE',
    fullName: 'SBI SimplySAVE Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #b71c1c 0%, #c62828 50%, #d32f2f 100%)',
    textColor: '#ffffff',
    accentColor: '#ef9a9a',
    tier: 'entry',
  },
  {
    id: 'sbi-elite',
    bank: 'sbi',
    cardName: 'ELITE',
    fullName: 'SBI Card ELITE',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #0d1b2a 0%, #1b2838 50%, #1a4c8b 100%)',
    textColor: '#ffffff',
    accentColor: '#d4af37',
    tier: 'premium',
  },
  {
    id: 'sbi-prime',
    bank: 'sbi',
    cardName: 'PRIME',
    fullName: 'SBI Card PRIME',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #0a0a0a 0%, #1a1a1a 50%, #2d2d2d 100%)',
    textColor: '#ffffff',
    accentColor: '#d4af37',
    tier: 'premium',
  },
  {
    id: 'sbi-air-india-signature',
    bank: 'sbi',
    cardName: 'Air India Signature',
    fullName: 'Air India SBI Signature Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #c62828 0%, #e53935 50%, #ef5350 100%)',
    textColor: '#ffffff',
    accentColor: '#ffcdd2',
    tier: 'premium',
  },

  // American Express
  {
    id: 'amex-platinum',
    bank: 'amex',
    cardName: 'Platinum',
    fullName: 'American Express Platinum Card',
    network: 'amex',
    gradient: 'linear-gradient(135deg, #78909c 0%, #90a4ae 50%, #b0bec5 100%)',
    textColor: '#1a1a1a',
    accentColor: '#cfd8dc',
    tier: 'super_premium',
  },
  {
    id: 'amex-platinum-travel',
    bank: 'amex',
    cardName: 'Platinum Travel',
    fullName: 'American Express Platinum Travel Credit Card',
    network: 'amex',
    gradient: 'linear-gradient(135deg, #b8860b 0%, #daa520 50%, #ffd700 100%)',
    textColor: '#1a1a1a',
    accentColor: '#fff8e1',
    tier: 'premium',
  },
  {
    id: 'amex-mrcc',
    bank: 'amex',
    cardName: 'Membership Rewards',
    fullName: 'American Express Membership Rewards Credit Card',
    network: 'amex',
    gradient: 'linear-gradient(135deg, #004d40 0%, #00695c 50%, #00796b 100%)',
    textColor: '#ffffff',
    accentColor: '#80cbc4',
    tier: 'mid',
  },
  {
    id: 'amex-smartearn',
    bank: 'amex',
    cardName: 'SmartEarn',
    fullName: 'American Express SmartEarn Credit Card',
    network: 'amex',
    gradient: 'linear-gradient(135deg, #0d47a1 0%, #1565c0 50%, #1976d2 100%)',
    textColor: '#ffffff',
    accentColor: '#64b5f6',
    tier: 'entry',
  },

  // IDFC FIRST Bank
  {
    id: 'idfc-wealth',
    bank: 'idfc_first',
    cardName: 'Wealth',
    fullName: 'IDFC FIRST Wealth Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #0a0a0a 0%, #1a1a1a 50%, #2d2d2d 100%)',
    textColor: '#ffffff',
    accentColor: '#d4af37',
    tier: 'super_premium',
  },
  {
    id: 'idfc-select',
    bank: 'idfc_first',
    cardName: 'Select',
    fullName: 'IDFC FIRST Select Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #0d1b2a 0%, #1b3a5c 50%, #1a4c8b 100%)',
    textColor: '#ffffff',
    accentColor: '#90caf9',
    tier: 'premium',
  },
  {
    id: 'idfc-millennia',
    bank: 'idfc_first',
    cardName: 'Millennia',
    fullName: 'IDFC FIRST Millennia Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #00695c 0%, #00897b 50%, #26a69a 100%)',
    textColor: '#ffffff',
    accentColor: '#b2dfdb',
    tier: 'mid',
  },
  {
    id: 'idfc-classic',
    bank: 'idfc_first',
    cardName: 'Classic',
    fullName: 'IDFC FIRST Classic Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #546e7a 0%, #78909c 50%, #90a4ae 100%)',
    textColor: '#ffffff',
    accentColor: '#cfd8dc',
    tier: 'entry',
  },

  // IndusInd Bank
  {
    id: 'indusind-legend',
    bank: 'indusind',
    cardName: 'Legend',
    fullName: 'IndusInd Bank Legend Credit Card',
    network: 'mastercard',
    gradient: 'linear-gradient(135deg, #0a0a0a 0%, #1a1a1a 50%, #2d2d2d 100%)',
    textColor: '#ffffff',
    accentColor: '#d4af37',
    tier: 'super_premium',
  },
  {
    id: 'indusind-pinnacle',
    bank: 'indusind',
    cardName: 'Pinnacle',
    fullName: 'IndusInd Bank Pinnacle Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #1a0033 0%, #2d004d 50%, #4a0080 100%)',
    textColor: '#ffffff',
    accentColor: '#ce93d8',
    tier: 'premium',
  },
  {
    id: 'indusind-aura-edge',
    bank: 'indusind',
    cardName: 'Aura Edge',
    fullName: 'IndusInd Bank Aura Edge Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #0d47a1 0%, #1976d2 50%, #42a5f5 100%)',
    textColor: '#ffffff',
    accentColor: '#90caf9',
    tier: 'mid',
  },

  // Kotak Mahindra Bank
  {
    id: 'kotak-zenith',
    bank: 'kotak',
    cardName: 'Zenith',
    fullName: 'Kotak Zenith Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #0a0a0a 0%, #1a1a1a 50%, #2d2d2d 100%)',
    textColor: '#ffffff',
    accentColor: '#d4af37',
    tier: 'super_premium',
  },
  {
    id: 'kotak-royale-signature',
    bank: 'kotak',
    cardName: 'Royale Signature',
    fullName: 'Kotak Royale Signature Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #4a0e0e 0%, #6b1a1a 50%, #8b2222 100%)',
    textColor: '#ffffff',
    accentColor: '#d4af37',
    tier: 'premium',
  },
  {
    id: 'kotak-league-platinum',
    bank: 'kotak',
    cardName: 'League Platinum',
    fullName: 'Kotak League Platinum Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #455a64 0%, #607d8b 50%, #78909c 100%)',
    textColor: '#ffffff',
    accentColor: '#b0bec5',
    tier: 'mid',
  },

  // Standard Chartered
  {
    id: 'sc-ultimate',
    bank: 'sc',
    cardName: 'Ultimate',
    fullName: 'Standard Chartered Ultimate Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #0a0a0a 0%, #1a1a1a 50%, #2d2d2d 100%)',
    textColor: '#ffffff',
    accentColor: '#78909c',
    tier: 'super_premium',
  },
  {
    id: 'sc-smart',
    bank: 'sc',
    cardName: 'Smart',
    fullName: 'Standard Chartered Smart Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #0072aa 0%, #0090d4 50%, #00aaff 100%)',
    textColor: '#ffffff',
    accentColor: '#80d8ff',
    tier: 'mid',
  },
  {
    id: 'sc-manhattan',
    bank: 'sc',
    cardName: 'Manhattan Rewards',
    fullName: 'Standard Chartered Manhattan Rewards Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #b71c1c 0%, #d32f2f 50%, #e53935 100%)',
    textColor: '#ffffff',
    accentColor: '#ef9a9a',
    tier: 'mid',
  },

  // YES Bank
  {
    id: 'yes-marquee',
    bank: 'yes',
    cardName: 'Marquee',
    fullName: 'YES Marquee Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #0a0a0a 0%, #1a1a1a 50%, #2d2d2d 100%)',
    textColor: '#ffffff',
    accentColor: '#d4af37',
    tier: 'super_premium',
  },
  {
    id: 'yes-reserv',
    bank: 'yes',
    cardName: 'Reserv',
    fullName: 'YES Reserv Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #b8860b 0%, #daa520 50%, #ffd700 100%)',
    textColor: '#000000',
    accentColor: '#fff8e1',
    tier: 'premium',
  },
  {
    id: 'yes-premia',
    bank: 'yes',
    cardName: 'Premia',
    fullName: 'YES Premia Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #0061a8 0%, #0079d3 50%, #0091ff 100%)',
    textColor: '#ffffff',
    accentColor: '#90caf9',
    tier: 'mid',
  },

  // AU Small Finance Bank
  {
    id: 'au-zenith',
    bank: 'au',
    cardName: 'Zenith',
    fullName: 'AU Small Finance Bank Zenith Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #0a0a0a 0%, #1a1a1a 50%, #2d2d2d 100%)',
    textColor: '#ffffff',
    accentColor: '#d4af37',
    tier: 'premium',
  },
  {
    id: 'au-vetta',
    bank: 'au',
    cardName: 'Vetta',
    fullName: 'AU Small Finance Bank Vetta Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #ec6608 0%, #f57c00 50%, #ff9800 100%)',
    textColor: '#ffffff',
    accentColor: '#ffe0b2',
    tier: 'mid',
  },

  // RBL Bank
  {
    id: 'rbl-world-safari',
    bank: 'rbl',
    cardName: 'World Safari',
    fullName: 'RBL Bank World Safari Credit Card',
    network: 'mastercard',
    gradient: 'linear-gradient(135deg, #1b5e20 0%, #2e7d32 50%, #4caf50 100%)',
    textColor: '#ffffff',
    accentColor: '#a5d6a7',
    tier: 'premium',
  },
  {
    id: 'rbl-icon',
    bank: 'rbl',
    cardName: 'Icon',
    fullName: 'RBL Bank Icon Credit Card',
    network: 'mastercard',
    gradient: 'linear-gradient(135deg, #b71c1c 0%, #21409a 50%, #0d47a1 100%)',
    textColor: '#ffffff',
    accentColor: '#90caf9',
    tier: 'mid',
  },
  {
    id: 'rbl-bajaj-supercard',
    bank: 'rbl',
    cardName: 'Bajaj SuperCard',
    fullName: 'Bajaj Finserv RBL Bank SuperCard',
    network: 'mastercard',
    gradient: 'linear-gradient(135deg, #0d47a1 0%, #1565c0 50%, #1976d2 100%)',
    textColor: '#ffffff',
    accentColor: '#64b5f6',
    tier: 'mid',
  },
  // Federal Bank (6 cards)
  {
    id: 'federal-celesta',
    bank: 'federal',
    cardName: 'Celesta',
    fullName: 'Federal Bank Celesta Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #0d1b2a 0%, #1b3a5c 50%, #274c77 100%)',
    textColor: '#ffffff',
    accentColor: '#d4af37',
    tier: 'premium',
  },
  {
    id: 'federal-imperio',
    bank: 'federal',
    cardName: 'Imperio',
    fullName: 'Federal Bank Imperio Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%)',
    textColor: '#ffffff',
    accentColor: '#e94560',
    tier: 'mid',
  },
  {
    id: 'federal-signet',
    bank: 'federal',
    cardName: 'Signet',
    fullName: 'Federal Bank Signet Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #0066B3 0%, #0080d4 50%, #0099e6 100%)',
    textColor: '#ffffff',
    accentColor: '#ffffff',
    tier: 'entry',
  },
  {
    id: 'federal-signet-rupay',
    bank: 'federal',
    cardName: 'Signet RuPay',
    fullName: 'Federal Bank Signet RuPay Credit Card',
    network: 'rupay',
    gradient: 'linear-gradient(135deg, #003366 0%, #005599 50%, #0077cc 100%)',
    textColor: '#ffffff',
    accentColor: '#80d0ff',
    tier: 'entry',
  },
  {
    id: 'federal-scapia',
    bank: 'federal',
    cardName: 'Scapia',
    fullName: 'Scapia Federal Bank Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #0a0a0a 0%, #1e1e2f 50%, #2d1b69 100%)',
    textColor: '#ffffff',
    accentColor: '#7c3aed',
    tier: 'mid',
  },
  {
    id: 'federal-starbiz',
    bank: 'federal',
    cardName: 'Fed StarBiz',
    fullName: 'Federal Bank Fed StarBiz Visa Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #004080 0%, #0060a0 50%, #0080c0 100%)',
    textColor: '#ffffff',
    accentColor: '#ffd700',
    tier: 'entry',
  },
  // Indian Bank (3 cards)
  {
    id: 'indian-bank-one',
    bank: 'indian_bank',
    cardName: 'Indian Bank One',
    fullName: 'Indian Bank One Co-Branded Credit Card',
    network: 'rupay',
    gradient: 'linear-gradient(135deg, #1a1a1a 0%, #2d2d2d 30%, #404040 100%)',
    textColor: '#ffffff',
    accentColor: '#2B2D8E',
    tier: 'mid',
  },
  {
    id: 'indian-bank-gold',
    bank: 'indian_bank',
    cardName: 'Gold',
    fullName: 'Indian Bank Gold Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #2B2D8E 0%, #3d3faa 50%, #5052cc 100%)',
    textColor: '#ffffff',
    accentColor: '#ffd700',
    tier: 'mid',
  },
  {
    id: 'indian-bank-classic',
    bank: 'indian_bank',
    cardName: 'Classic',
    fullName: 'Indian Bank Classic Credit Card',
    network: 'visa',
    gradient: 'linear-gradient(135deg, #1e1f6e 0%, #2B2D8E 50%, #3840a8 100%)',
    textColor: '#ffffff',
    accentColor: '#c0c0c0',
    tier: 'entry',
  },
];

/** Fuzzy match cardName against templates (case-insensitive, partial match). */
export function findCardTemplate(bank: Bank, cardName?: string): CardTemplate | undefined {
  if (!cardName || !cardName.trim()) {
    return getDefaultTemplate(bank);
  }
  const normalized = cardName.trim().toLowerCase().replace(/\s+/g, ' ');
  const bankTemplates = CARD_TEMPLATES.filter((t) => t.bank === bank);
  if (bankTemplates.length === 0) return undefined;

  // Exact match on cardName
  const exact = bankTemplates.find(
    (t) => t.cardName.toLowerCase() === normalized || t.cardName.toLowerCase().replace(/\s+/g, ' ') === normalized
  );
  if (exact) return exact;

  // Partial match: template name contains query or query contains template name
  const partial = bankTemplates.find(
    (t) =>
      t.cardName.toLowerCase().includes(normalized) ||
      normalized.includes(t.cardName.toLowerCase().replace(/\s+/g, ' '))
  );
  if (partial) return partial;

  // Word-level match
  const queryWords = normalized.split(/\s+/);
  const scored = bankTemplates.map((t) => {
    const name = t.cardName.toLowerCase();
    let score = 0;
    for (const w of queryWords) {
      if (name.includes(w)) score += 1;
    }
    return { template: t, score };
  });
  const best = scored.filter((s) => s.score > 0).sort((a, b) => b.score - a.score)[0];
  return best?.template;
}

/** Returns the bank's most popular card as default. */
export function getDefaultTemplate(bank: Bank): CardTemplate {
  const defaults: Record<Bank, string> = {
    hdfc: 'hdfc-regalia',
    icici: 'icici-amazon-pay',
    axis: 'axis-flipkart',
    sbi: 'sbi-elite',
    amex: 'amex-platinum',
    idfc_first: 'idfc-wealth',
    indusind: 'indusind-legend',
    kotak: 'kotak-zenith',
    sc: 'sc-ultimate',
    yes: 'yes-marquee',
    au: 'au-zenith',
    rbl: 'rbl-world-safari',
    federal: 'federal-celesta',
    indian_bank: 'indian-bank-one',
  };
  const id = defaults[bank];
  const found = CARD_TEMPLATES.find((t) => t.id === id);
  if (found) return found;
  const fallback = CARD_TEMPLATES.find((t) => t.bank === bank);
  return fallback ?? CARD_TEMPLATES[0]!;
}
